schema:
  - http://localhost:4000/graphql
documents:
  - "src/**/*.{tsx,ts}"
generates:
  src/__generated__/global.ts:
    differentFiles: true
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withRefetchFn: true
      withHooks: true
      withComponent: false
      withHOC: false
    overwrite:
      - true
